# Config Module
from .config import (
    PROJECT_ROOT,
    BACKEND_ROOT,
    FOLDERS,
    GEMINI_PROJECT_ID,
    GEMINI_LOCATION,
    GEMINI_CREDENTIALS,
    GEMINI_OCR_MODEL,
    GEMINI_LLM_MODEL,
    OPENAI_MODEL,
    JUDGE_PROVIDER,
    JUDGE_MODEL,
    MODEL_LIMITS,
    setup_logging
)

__all__ = [
    "PROJECT_ROOT",
    "BACKEND_ROOT",
    "FOLDERS",
    "GEMINI_PROJECT_ID",
    "GEMINI_LOCATION",
    "GEMINI_CREDENTIALS",
    "GEMINI_OCR_MODEL",
    "GEMINI_LLM_MODEL",
    "OPENAI_MODEL",
    "JUDGE_PROVIDER",
    "JUDGE_MODEL",
    "MODEL_LIMITS",
    "setup_logging"
]
